# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'baglan_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowBaglan(object):
    def setupUi(self, MainWindowBaglan):
        MainWindowBaglan.setObjectName("MainWindowBaglan")
        MainWindowBaglan.resize(762, 398)
        self.centralwidget = QtWidgets.QWidget(MainWindowBaglan)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.DATABASEADI = QtWidgets.QLineEdit(self.centralwidget)
        self.DATABASEADI.setObjectName("DATABASEADI")
        self.gridLayout.addWidget(self.DATABASEADI, 4, 0, 1, 1)
        self.baglanButton = QtWidgets.QPushButton(self.centralwidget)
        self.baglanButton.setObjectName("baglanButton")
        self.gridLayout.addWidget(self.baglanButton, 5, 0, 1, 1)
        self.SERVERADI = QtWidgets.QLineEdit(self.centralwidget)
        self.SERVERADI.setObjectName("SERVERADI")
        self.gridLayout.addWidget(self.SERVERADI, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.bilgilendirme_label = QtWidgets.QLabel(self.centralwidget)
        self.bilgilendirme_label.setText("")
        self.bilgilendirme_label.setObjectName("bilgilendirme_label")
        self.gridLayout.addWidget(self.bilgilendirme_label, 6, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindowBaglan.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowBaglan)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 762, 26))
        self.menubar.setObjectName("menubar")
        MainWindowBaglan.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowBaglan)
        self.statusbar.setObjectName("statusbar")
        MainWindowBaglan.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowBaglan)
        QtCore.QMetaObject.connectSlotsByName(MainWindowBaglan)

    def retranslateUi(self, MainWindowBaglan):
        _translate = QtCore.QCoreApplication.translate
        MainWindowBaglan.setWindowTitle(_translate("MainWindowBaglan", "MainWindow"))
        self.label.setText(_translate("MainWindowBaglan", "DATABASE:"))
        self.label_3.setText(_translate("MainWindowBaglan", "Veritabanını Giriniz"))
        self.baglanButton.setText(_translate("MainWindowBaglan", "Baglan"))
        self.label_2.setText(_translate("MainWindowBaglan", "SERVER ADI:"))
