# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'musteri_biletlerim_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowMusBiletler(object):
    def setupUi(self, MainWindowMusBiletler):
        MainWindowMusBiletler.setObjectName("MainWindowMusBiletler")
        MainWindowMusBiletler.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindowMusBiletler)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 1, 0, 1, 3)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        MainWindowMusBiletler.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowMusBiletler)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindowMusBiletler.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowMusBiletler)
        self.statusbar.setObjectName("statusbar")
        MainWindowMusBiletler.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowMusBiletler)
        QtCore.QMetaObject.connectSlotsByName(MainWindowMusBiletler)

    def retranslateUi(self, MainWindowMusBiletler):
        _translate = QtCore.QCoreApplication.translate
        MainWindowMusBiletler.setWindowTitle(_translate("MainWindowMusBiletler", "Biletlerim"))
        self.pushButton_2.setText(_translate("MainWindowMusBiletler", "Profil"))
        self.pushButton.setText(_translate("MainWindowMusBiletler", "Ana Sayfa"))
        self.pushButton_4.setText(_translate("MainWindowMusBiletler", "Yenile"))
