# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'personel_profil_ekrani_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowPerProfil(object):
    def setupUi(self, MainWindowPerProfil):
        MainWindowPerProfil.setObjectName("MainWindowPerProfil")
        MainWindowPerProfil.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindowPerProfil)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.adSoyadLabel = QtWidgets.QLabel(self.centralwidget)
        self.adSoyadLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.adSoyadLabel.setObjectName("adSoyadLabel")
        self.gridLayout.addWidget(self.adSoyadLabel, 6, 2, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 9, 0, 1, 2)
        self.telNoLabel = QtWidgets.QLabel(self.centralwidget)
        self.telNoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.telNoLabel.setObjectName("telNoLabel")
        self.gridLayout.addWidget(self.telNoLabel, 8, 2, 1, 2)
        self.departmanLabel = QtWidgets.QLabel(self.centralwidget)
        self.departmanLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.departmanLabel.setObjectName("departmanLabel")
        self.gridLayout.addWidget(self.departmanLabel, 7, 2, 1, 2)
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.usernameLabel.setObjectName("usernameLabel")
        self.gridLayout.addWidget(self.usernameLabel, 9, 2, 1, 2)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 6, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 7, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 8, 0, 1, 2)
        self.yenileButton = QtWidgets.QPushButton(self.centralwidget)
        self.yenileButton.setObjectName("yenileButton")
        self.gridLayout.addWidget(self.yenileButton, 2, 2, 1, 2)
        self.anaSayfaButton = QtWidgets.QPushButton(self.centralwidget)
        self.anaSayfaButton.setObjectName("anaSayfaButton")
        self.gridLayout.addWidget(self.anaSayfaButton, 2, 0, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        MainWindowPerProfil.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindowPerProfil)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindowPerProfil.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindowPerProfil)
        self.statusbar.setObjectName("statusbar")
        MainWindowPerProfil.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindowPerProfil)
        QtCore.QMetaObject.connectSlotsByName(MainWindowPerProfil)

    def retranslateUi(self, MainWindowPerProfil):
        _translate = QtCore.QCoreApplication.translate
        MainWindowPerProfil.setWindowTitle(_translate("MainWindowPerProfil", "Personel Profil Ekranı"))
        self.adSoyadLabel.setText(_translate("MainWindowPerProfil", "NONE"))
        self.label_5.setText(_translate("MainWindowPerProfil", "KULLANICI ADI:"))
        self.telNoLabel.setText(_translate("MainWindowPerProfil", "NONE"))
        self.departmanLabel.setText(_translate("MainWindowPerProfil", "NONE"))
        self.usernameLabel.setText(_translate("MainWindowPerProfil", "NONE"))
        self.label.setText(_translate("MainWindowPerProfil", "İSİM SOYİSİM: "))
        self.label_3.setText(_translate("MainWindowPerProfil", "DEPATMAN:"))
        self.label_4.setText(_translate("MainWindowPerProfil", "TELEFON NUMARASI:"))
        self.yenileButton.setText(_translate("MainWindowPerProfil", "Yenile"))
        self.anaSayfaButton.setText(_translate("MainWindowPerProfil", "Ana Sayfa"))
